name: restaurant_menu
description: Manage your Menu with ease
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^2.18.0
  firebase_database: ^10.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  go_router: ^10.1.2
  http: ^1.1.0
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
      - assets/background.jpg
