// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0sXHRnUyLREZA1CrSXN_xswMVfGEAKOI',
    appId: '1:446513084286:android:950788980e84ab2938a52f',
    messagingSenderId: '446513084286',
    projectId: 'restaurant-menu-b78e9',
    databaseURL: 'https://restaurant-menu-b78e9-default-rtdb.firebaseio.com',
    storageBucket: 'restaurant-menu-b78e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZmYN5Kj9kfhcq2vKTRmaSuFUhiQFpHfs',
    appId: '1:446513084286:ios:ac7eb51dae4081e938a52f',
    messagingSenderId: '446513084286',
    projectId: 'restaurant-menu-b78e9',
    databaseURL: 'https://restaurant-menu-b78e9-default-rtdb.firebaseio.com',
    storageBucket: 'restaurant-menu-b78e9.appspot.com',
    iosBundleId: 'com.yojacni.restaurant-menu',
  );
}
